import = ["~/.config/alacritty/gruvbox_dark.toml", "~/.config/alacritty/fonts.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

# [shell]
# program = "tmux"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.90

[keyboard]
[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"


[cursor]
style = { shape = "Block", blinking = "On" } 
