add_newline = true

[line_break]
disabled = false

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "../"
read_only_style = "red"
read_only = " 牢"

[character]
success_symbol = "[➜](bold cyan) "
error_symbol = "[✗](bold red) "

[git_branch]
style = "bold purple"
symbol = " "
truncation_length = 6
truncation_symbol = ""

# shows the hostname on new lines
[hostname]
ssh_only = false
format = "[$hostname]($style): "
style = "bold blue"

[username]
style_user = "bold yellow"
style_root = "bold green"
format = "[$user]($style)@"
disabled = false
show_always = true
